
CREATE USER backend_dev WITH PASSWORD 'ifunggul';
GRANT CONNECT ON DATABASE postgres TO backend_dev;
GRANT USAGE ON SCHEMA salam TO backend_dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA salam TO backend_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA salam GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO backend_dev;

CREATE USER bi_dev WITH PASSWORD 'ifunggul';
GRANT CONNECT ON DATABASE postgres TO bi_dev;
GRANT USAGE ON SCHEMA salam TO bi_dev;
GRANT SELECT ON ALL TABLES IN SCHEMA salam TO bi_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA salam GRANT SELECT ON TABLES TO bi_dev;

CREATE USER data_engineer WITH PASSWORD 'ifunggul';
GRANT CONNECT ON DATABASE postgres TO data_engineer;
GRANT USAGE, CREATE ON SCHEMA salam TO data_engineer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA salam TO data_engineer;
ALTER DEFAULT PRIVILEGES IN SCHEMA salam GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO data_engineer;
